"""create_profile_table

Revision ID: 70369e29012e
Revises: 
Create Date: 2025-06-22 00:01:02.367605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '70369e29012e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('data', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('caregivers',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('phone_number', sa.String(), nullable=True),
                    sa.Column('relationship_type', sa.String(), nullable=True),
                    sa.Column('receive_alerts', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('topics',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('profiles',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), nullable=False),
                    sa.Column('full_name', sa.String(), nullable=True),
                    sa.Column('dob', sa.Date(), nullable=True),
                    sa.Column('phone_number', sa.String(), nullable=True),
                    sa.Column('preferred_speech_speed',
                              sa.Float(), nullable=True),
                    sa.Column('preferred_avatar_type',
                              sa.String(), nullable=True),
                    sa.Column('accessibility_preferences', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('caregiver_id', sa.UUID(), nullable=True),
                    sa.Column('last_login', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['caregiver_id'], ['caregivers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_profiles_email'),
                    'profiles', ['email'], unique=True)
    op.create_index(op.f('ix_profiles_full_name'),
                    'profiles', ['full_name'], unique=False)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('medications',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('profile_id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('dosage', sa.String(), nullable=True),
                    sa.Column('frequency', sa.String(), nullable=True),
                    sa.Column('time_of_day', sa.ARRAY(
                        sa.String()), nullable=False),
                    sa.Column('instructions', sa.Text(), nullable=True),
                    sa.Column('start_date', sa.Date(), nullable=False),
                    sa.Column('end_date', sa.Date(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('sessions',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('profile_id', sa.UUID(), nullable=False),
                    sa.Column('start_time', sa.TIMESTAMP(
                        timezone=True), nullable=False),
                    sa.Column('end_time', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('duration', sa.Integer(), nullable=True),
                    sa.Column('mood_score', sa.Integer(), nullable=True),
                    sa.Column('mood_notes', sa.Text(), nullable=True),
                    sa.Column('time_of_day', sa.String(), nullable=True),
                    sa.Column('summary', sa.Text(), nullable=True),
                    sa.Column('has_activity', sa.Boolean(), nullable=True),
                    sa.Column('activity_type', sa.String(), nullable=True),
                    sa.Column('activity_id', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['activity_id'], ['activities.id'], ),
                    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('chat_turns',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('session_id', sa.UUID(), nullable=False),
                    sa.Column('timestamp', sa.TIMESTAMP(
                        timezone=True), nullable=False),
                    sa.Column('speaker', sa.String(), nullable=False),
                    sa.Column('message', sa.Text(), nullable=False),
                    sa.Column('audio_url', sa.String(), nullable=True),
                    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(
                        dim=1536), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('medication_reminders',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('medication_id', sa.UUID(), nullable=False),
                    sa.Column('scheduled_time', sa.TIMESTAMP(
                        timezone=True), nullable=False),
                    sa.Column('taken_time', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('skipped', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['medication_id'], ['medications.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('notes',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('session_id', sa.UUID(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('content', sa.Text(), nullable=True),
                    sa.Column('is_important', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('session_activities',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('session_id', sa.UUID(), nullable=False),
                    sa.Column('activity_id', sa.UUID(), nullable=False),
                    sa.Column('start_time', sa.TIMESTAMP(
                        timezone=True), nullable=False),
                    sa.Column('end_time', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.Column('score', sa.Integer(), nullable=True),
                    sa.Column('results', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['activity_id'], ['activities.id'], ),
                    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('session_topics',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('session_id', sa.UUID(), nullable=False),
                    sa.Column('topic_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
                    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_topics')
    op.drop_table('session_activities')
    op.drop_table('notes')
    op.drop_table('medication_reminders')
    op.drop_table('chat_turns')
    op.drop_table('sessions')
    op.drop_table('medications')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_full_name'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('topics')
    op.drop_table('caregivers')
    op.drop_table('activities')
    # ### end Alembic commands ###
